* auth-source-kwallet

  [[https://melpa.org/#/auth-source-kwallet][file:https://melpa.org/packages/auth-source-kwallet-badge.svg]]
  [[https://melpa.org/#/auth-source-kwallet][file:https://stable.melpa.org/packages/auth-source-kwallet-badge.svg]]

  This package allows one to use KWallet as an auth-source. While KWallet may not be the best thing ever,
  it works pretty well with KDE, so I decided to make this package.

** Usage

   If you are using [[https://github.com/jwiegley/use-package][use-package]], you may install the package using with the following code:

   #+BEGIN_SRC elisp
     (use-package auth-source-kwallet
       :config
       (auth-source-kwallet-enable))
   #+END_SRC

   To enable the auth source, use ~(auth-source-kwallet-enable)~, like in the example above with use-package.

** Configuration

   The following parameters can be customized:

   - ~auth-source-kwallet-wallet~ :: Default value: "Passwords"

     The wallet to use.
   - ~auth-source-kwallet-folder~ :: Default value: "Passwords"

     The folder to use in the wallet.
   - ~auth-source-kwallet-key-separator~ :: Default value: "@"

     The value used to separate the name and the host when looking up
     the key key in the wallet.
   - ~auth-source-kwallet-executable~ :: Default value: "kwallet-query"

     Executable used to query kwallet.

   So, for example, with the default settings, for hostname of "example.com" and username of "test",
   the secret will be looked up in the Passwords wallet, Passwords folder, under the name
   "test@example.com".
